### ISSUE TITLE
Positionning is taken from target event element. 

### ISSUE THREAD

**Issue by MarkOdey** [kramer99/vue-knob-control#13]
Hey guys, I think I understand one of the reason why the numbers were sometimes behaving a little chaotic. 

When your mouse is moving outside the element of concern it was using the offset position within this dom element. 

I am using the mouse position from the client position now so the target won't matter and using the getBoundClientRect to get the center of the knob.

It works pretty well on my fork. 

Do you want me to issue PR?

**Comment by kramer99** [comment]
I'm not sure I follow. 

Are you saying you have a change which handles mouse movement better?

You're welcome to open a PR, it will be more likely to be accepted if it is small and doesn't alter the API.

**Comment by MarkOdey** [comment]
Ok let me setup a PR .

**Comment by kramer99** [comment]
Closed matching PR due to inactivity.
