### ISSUE TITLE
No Mobile Support

### ISSUE THREAD

**Issue by melissaep** [kramer99/vue-knob-control#4]
It looks like only mouse events are being listened to, would you have any recommendations on how I may be able to listen for touch events in order to support mobile?

I tried changing the @click, @mousedown, @mouseup events to the touch event equivalents, but the "offsetX" and "offsetY" properties aren't available on TouchEvents so the updatePosition calculation breaks.

**Comment by kramer99** [comment]
@melissaep Grab the latest from NPM and let me know if it functions correctly for you. I've tested it using mobile simulation mode in Chrome, not on a physical device.

**Comment by melissaep** [comment]
Works perfectly - tested on iOS. Thanks so much!
