### ISSUE TITLE
this.valueDisplayFunction is not a function

### ISSUE THREAD

**Issue by timenengwerda** [kramer99/vue-knob-control#5]
In your computed where you set the textValue you call a method that doesn't exist

**Comment by timenengwerda** [comment]
Nvm, I'm an idiot; I HAVE to put in a function apparently. It would be nice if a normal value could be passed though. Same goes for some extra events(touchEnd emit for example

**Comment by kramer99** [comment]
You don't need to supply a valueDisplayFunction at all, see line 94: it defaults to (v) => v, as per the documentation.
