### ISSUE TITLE
mousedown event not working

### ISSUE THREAD

**Issue by mapkbalaji** [kramer99/vue-knob-control#6]
Hi,
Is it possible to get status if the slider is being moved. When I use @click.native="mousedown" in <knob-control> parameters, I get the following error:

"Ignored attempt to cancel a touchstart event with cancelable=false, for example because scrolling is in progress and cannot be interrupted."

Or, isn't there any onChange event? 

I'm trying to interlink 4 knobs, and so, if one knob is slided, I needed to set an active flag to it and remove active flags on all other knobs.

**Comment by kramer99** [comment]
So this is a feature request?

If you want to link the knobs, you could set them to all have the same v-model.

**Comment by kramer99** [comment]
Closing due to non-response.
